### ISSUE TITLE
Organization members are not public makes it hard to see who's in charge

### ISSUE THREAD

**Issue by rjmunro** [gitx/gitx.github.io#2]
#If you look at the organisation home page (https://github.com/orgs/gitx/people) it says "This organization has no public members". As this is a critical part of all development for me and many other people, I think it would be good if members of the organisation set themselves public.

**Comment by nanoant** [comment]
That's up to the members to publish their membership. Moreover, I think you need to give @ssp @claybridges some time to set up everything, as they have just (re-)started discussing the reunion of GitX here in #1.

**Comment by rjmunro** [comment]
@nanoant Sure, I realised it is up to individuals to enable themselves as public. Sorry if the request came over a bit too strongly - I don't know any other way to talk to the group other than with Issues on this repo.

**Comment by claybridges** [comment]
I'm pretty sure we can set up the Core team membership as public as a team ste

**Comment by claybridges** [comment]
I set the core team membership to public. If anybody objects, let me know or feel free to switch it back. @rjmunro Let me know if this doesn't help.
